version: "3.5"
services:
  node:
    build: .
    container_name: shopping-service
    environment:
      - NODE_ENV=development
      - PORT=3200
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3200:3200
    command: "npm run dev"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"
