version: "3.5"
services:
  api:
    build: .
    ports:
    - "3200:3200"
    environment:
      - SECRET=ps120fadrn58d9aw
      - APP_PORT=3200
      - APP_HOST=localhost
      - DB_URI=mongodb://db:27017/shopping-list
    depends_on:
    - db
  db:
    image: mongo
    ports:
    - "27017:27017"